### ISSUE TITLE
Jumps to desktop in OSX 10.15

### ISSUE THREAD

**Issue by JepsonNomad** [nvkelso/color-oracle#14]
I just made the update to Mac OSX 10.15 Catalina. Now, when opening Color Oracle, whatever I'm looking at jumps to the desktop (the windows "fly away"), and I only see the desktop in Protanopia, etc. Still able to cycle through color versions, but only while looking at the desktop...

**Comment by jsluys** [comment]
Same issue here.

**Comment by JepsonNomad** [comment]
Issue solved by enabling screen recording under Privacy tab of Security & Privacy settings.
