### ISSUE TITLE
Stopped working after upgrade to macOS Sierra v10.12

### ISSUE THREAD

**Issue by fionnayao** [nvkelso/color-oracle#6]
Hi, Color Oracle seems to stop working for me after upgrade to Sierra.

Checked on the following screens: 
1. MacBook Pro Retina, 15-inch, Early 2013
2. ASUS VW248 Display 24-inch 

Thanks for your great work. This app has been invaluable to me :)

**Comment by kachkaev** [comment]
I've just installed `1.1.4` on macOS High Sierra and noticed that Color Oracle did not work on this OS too. The app launches, but none of the visual modes work. Feels like the app cannot make the screenshot and display it – confirmed this by opening the clock preferences and watching the hand moving even after triggering Color Oracle.

**Comment by leonmoonen** [comment]
Came here because I was looking for a 64-bit version. See that is still in the works, but I can confirm that version 1.1.4 works correctly for me on High Sierra (and on Sierra before).  

and yes, thanks for your great work!

**Comment by nvkelso** [comment]
New release is almost ready, thanks for your patience.

**Comment by berniejenny** [comment]
Please try the new version 1.3, which should work with macOS Sierra and High Sierra.
