### ISSUE TITLE
64-bit version for macOS 10.14

### ISSUE THREAD

**Issue by berniejenny** [nvkelso/color-oracle#8]

**Comment by kachkaev** [comment]
@berniejenny does Color Oracle work for you at all on macOS 10.13? Just curious. See https://github.com/nvkelso/color-oracle/issues/6.

**Comment by leonmoonen** [comment]
@kachkaev @berniejenny 1.1.4 works well for me on macOS 10.13, also a 64-bit version seems to be readily [available as a pull request](https://github.com/nvkelso/color-oracle/pull/7)

**Comment by berniejenny** [comment]
Color Oracle 1.3 is now 64-bit code and works on macOS 10.13.
